spring:
  datasource:
    url: jdbc:mysql://mysql:3306/apartment_identity?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: identity
    password: identity
  redis:
    host: redis
    port: 6379

---

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@discovery:8761/eureka
