spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: notification
  redis:
    host: redis
    port: 6379
  mail:
    host: greenmail
    port: 3025
    username: noreply
    password: admin1!

---

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@discovery:8761/eureka

---

apartment:
  notification:
    email:
      from: noreply@apartment.vn
      bcc: noreply@apartment.vn
      max-retry-times: 3