version: "3.9"
services:

  nginx: # Nginx HTTP/HTTPS
    image: nginx:1.20
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - shared_env_net
      - env_net
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/ssl/nginx.crt:/etc/ssl/certs/nginx.crt
      - ./nginx/ssl/nginx.key:/etc/ssl/private/nginx.key
      - ./nginx/ssl/dhparams.pem:/etc/ssl/private/dhparams.pem
      - ./nginx/www:/var/www/

  db: # MySQL
    image: mysql:8.0.22
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - shared_env_net
      - env_net
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --lower_case_table_names=1 --character_set_server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/entrypoint:/docker-entrypoint-initdb.d
      - env_db_vol:/var/lib/mysql

  mongodb: # Mongodb (NoSQL)
    image: mongo:4.4.2
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - env_mongodb_vol:/data/db
    networks:
      - shared_env_net
      - env_net

  redis: # Redis (Caching/Pub-Sub)
    image: redis:5.0.4
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
    networks:
      - shared_env_net
      - env_net

  greenmail: # Mock SMTP/IMAP e-Mail server
    image: greenmail/standalone:1.6.4
    container_name: greenmail
    restart: always
    ports:
      - 3025:3025 # SMTP
      - 3143:3143 # IMAP
      - 8181:8080 # GreenMail API
    environment:
      - GREENMAIL_OPTS=-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.users=noreply:admin1!@apartment.vn -Dgreenmail.verbose
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true -Xmx512m
    networks:
      - shared_env_net
      - env_net

  roundcube: # Web UI e-Mail
    image: roundcube/roundcubemail
    container_name: roundcube
    restart: always
    depends_on:
      - greenmail
    ports:
      - 8000:80
      - 9000:9000
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=greenmail
      - ROUNDCUBEMAIL_SMTP_SERVER=greenmail
      - ROUNDCUBEMAIL_SMTP_PORT=3025    # SMTP PORT
      - ROUNDCUBEMAIL_DEFAULT_PORT=3143 # IMAP PORT
    networks:
      - shared_env_net
      - env_net

  registry:  
    image: registry:2.7
    container_name: registry
    restart: always
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./hub/data:/data
    networks:
      - shared_env_net
      - env_net

volumes:
  env_db_vol:
  env_mongodb_vol:

networks:
  shared_env_net:
    external: true
  env_net:
    name: env_net
    driver: bridge