spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apartment_identity?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

---

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka

---